spring.application.name=PishuChat
# Настроили порт в который входим
server.port=9090
# Включает консоль H2 для управления БД через браузер (опционально)
spring.h2.console.enabled=true
# Использует встроенную БД в памяти (данные пропадут после перезапуска)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=di
spring.datasource.password=di
# Генерирует DDL из сущностей (@Entity)
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false  
# false для разработки

# Простая аутентификация (опционально)
spring.thymeleaf.prefix=classpath:/templates/
